baseURL = 'https://black-mushroom-0cae5de03.2.azurestaticapps.net/'
languageCode = 'en-us'
title = 'Home'
theme = 'ananke' 
author = "Emily Bakker"

[params]
  text_color = ""
  author = "Emily Bakker"
  favicon = ""
  site_logo = ""
  description = "PWS Napoleon en Hitler"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 8